# Generated by Django 3.2.13 on 2024-08-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number_phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
