# Generated by Django 3.2.13 on 2024-08-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_number_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number_phone',
            field=models.CharField(max_length=11),
        ),
    ]
